### PR TITLE
feat: add jvm benchmark for twitch4j and twirk

### PR DESCRIPTION
**Pull request by iProdigy**
Full benchmark suite runs in 20-30 seconds. Results are written to `./jvm/build/results/jmh/results.txt`

Sample output from my laptop:
```
Benchmark                (count)  Mode  Cnt     Score    Error  Units
Benchmarks.testTwirk        1000  avgt    5     5.442 ±  0.104  ms/op
Benchmarks.testTwitch4J     1000  avgt    5  1545.737 ± 27.606  us/op
```

I used Eclipse Adoptium 20.0.1+9, but there are other valid options. JDK 20 is the latest release, but Java 17 is the latest LTS version. Java 8 is the minimum possible version that can be used to run Twitch4J. In addition, there are other JDK builds [available](https://whichjdk.com/) than Eclipse Adoptium (JIT); Azul Zulu (JIT), BellSoft Liberica (JIT), Oracle GraalVM (AOT), etc. Technically, the fastest possible parser in (pure) Java would utilize the incubating Vector API (SIMD) and Project Valhalla (value classes), which currently requires using an [early access build](https://jdk.java.net/valhalla/), but no such irc parser implementation exists.

### CODE REVIEW

**Comment by neon-sunset** [comment]
You may want to add install and run instructions to `README.md`.

Also, while there are many JVM implementations, I think it's important to suggest the one that showcases most popular choice (is it OpenJDK?) yet latest performance improvements at the same time (like Rust, .NET and Go benchmarks do).

Out of personal curiosity, why does https://whichjdk.com/ shill `Adoptium` so much? I found no mentions of performance characteristics there even though it's a critical aspect which is very labour intensive when it comes to achieving competitive performance in such a complex VM.

Also, here are numbers on 5800X if you're interested (I changed measurement unit to microseconds):
```
Benchmark                (count)  Mode  Cnt     Score    Error  Units
Benchmarks.testTwirk        1000  avgt    5  2936.342 ┬▒ 67.854  us/op
Benchmarks.testTwitch4J     1000  avgt    5   959.507 ┬▒  3.370  us/op
```

**Comment by iProdigy** [comment]
Appreciate the comments @neon-sunset 

Could you elaborate on what type of instructions should be added to the readme (rn just says install temurin & run `./gradlew jmh`)?

OpenJDK is just a GPL implementation of java - the JIT VMs listed above essentially just repackage OpenJDK sources into binaries. Oracle also provides a OpenJDK build, but these only receive 6 months of updates (so people avoid these unless testing some early access version). Oracle's (commercial) JDK has longer support but comes with a problematic license (so folks also try to avoid this build). Out of the 3 JIT VMs in the OP, they should have the same performance (GraalVM, on the other hand, has a different performance profile with a faster start-up time but possibly lower throughput). Temurin (aka adoptium, formerly AdoptOpenJDK) is a centrist recommendation since it includes [members](https://adoptium.net/members/) from many other jdk providers. That said, I agree `whichjdk.com` pushes Temurin too hard given they're not on the [Vulnerability Group](https://openjdk.org/census#vulnerability), which can result in a few more days before CVEs are patched (imo irrelevant to benchmarking, though). In terms of popularity, it seems temurin is the most searched of the JIT options in the OP: https://trends.google.com/trends/explore?q=eclipse%20temurin,adoptopenjdk,azul%20zulu,zulu%20jdk,liberica%20jdk&hl=en

& thanks for sharing the output from your machine, I'll switch the PR to microseconds shortly

**Comment by neon-sunset** [comment]
> Could you elaborate on what type of instructions should be added to the readme (rn just says install temurin & run `./gradlew jmh`)?

This was a brain lag, I looked for `JVM` section in readme and could not find it when checked out at your branch and now I look at PR and...it is there 🤔

As for JVM choice - honestly, I have no idea hence the initial question, this was mostly about "what kind of performance would users of the latest release JVM implementation" expect because in .NET world this might be a significant difference in microbenchmarks between versions released in the last few years (6 vs 7 vs 8).

**Comment by iProdigy** [comment]
Most new applications are using JDK 17 - the performance difference between 17 & 20 is small (I just picked 20 since other langs use nightly/preview builds)

**Review by neon-sunset — APPROVED** [review]

**Comment by jprochazk** [comment]
I'll merge this in, but not sure when I'll get around to actually benchmarking it and updating the results.

**Pull request merged**
